---
- hosts: 127.0.0.1
  connection: local
  
  tasks:
  - name: Install desktop environment
    import_role:
      name: desktop

  - name: Install oh-my-zsh
    import_role:
      name: oh-my-zsh

  - name: Install vim
    import_role:
      name: vim

  - name: Install tmux
    import_role:
      name: tmux
