---
- name: Install zsh
  apt:
    name: zsh
    state: present
  become: true

- name: Download oh-my-zsh
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/zsh-install.sh
    mode: 0755

- name: Install oh-my-zsh
  command: /tmp/zsh-install.sh
  args:
    chdir: ~/
