---
- name: Install zsh
  apt:
    name: zsh
    state: present
  become: true

- name: Download vim source
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh


- name: Copy zshrc template from oh-my-zsh
  copy:
    src: .zshrc
    dest: ~/.zshrc

- name: Change shell to zsh
  user:
    name: hsatow
    shell: /bin/zsh
  become: true
